// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WareHousePlatForm.Data
{
    public partial class BoundData
    {
        public string UserName { get; set; }
        public string Name { get; set; }
        public string Category { get; set; }
        public int Unit { get; set; }
        public DateTime DateBorrow { get; set; }
        public DateTime? DateReturn { get; set; }
        public string Status { get; set; }
    }
}