// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WareHousePlatForm.Data
{
    public partial class ImportItem
    {
        public DateTime DateTime { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string Category { get; set; }
        public double? Price { get; set; }
        public int? Unit { get; set; }
        public string UserName { get; set; }
    }
}