// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WareHousePlatForm.Data
{
    public partial class ProductInformation
    {
        public string Name { get; set; }
        public string Code { get; set; }
        public string Category { get; set; }
        public int? Unit { get; set; }
        public int? UnitOfUsable { get; set; }
        public int? broken { get; set; }
        public int? Stock { get; set; }
    }
}